export const CRISIS_PROTOCOLS: Record<string, string[]> = {
  "man-overboard": [
    "Mark position (MOB button / GPS mark).",
    "Sound alarm — all hands.",
    "Assign a spotter to keep visual contact.",
    "Prepare rescue equipment.",
    "Begin the recovery maneuver.",
    "Log time and position.",
  ],
  "payload-drone": [
    "Clear all deck areas — no one topside.",
    "Do not approach the aircraft.",
    "Escalate to Support Center now.",
    "Keep the inbound bearing and altitude on the picture.",
    "Prepare to maneuver if it enters the exclusion zone.",
    "Log time, bearing, and description.",
  ],
  "drone-swarm": [
    "Escalate to Support Center — multiple contacts exceed local capacity.",
    "Keep a continuous track on the formation.",
    "Clear exposed decks and muster below.",
    "Ready the backup comms channel.",
    "Do not attempt a single-operator intercept.",
    "Log count, bearing, and first detection time.",
  ],
  "usv-swarm": [
    "Escalate immediately — this is a coordinated surface approach.",
    "Increase speed and prepare an evasive turn.",
    "Hail on VHF ch.16; assume no reply.",
    "Keep every contact on radar with a CPA watch.",
    "Warn crew of possible impact or wake.",
    "Log number, speed, and pattern.",
  ],
  "critical-closing-speed": [
    "Sound the horn — five or more short blasts.",
    "Alter course now; do not wait for a reply.",
    "Notify Support Center of the closest point of approach.",
    "Assign a visual spotter on the threat bearing.",
    "Set collision stations if range keeps closing.",
    "Log time, range, and the course change.",
  ],
  "uuv-payload": [
    "Escalate to Support Center immediately.",
    "Evacuate non-essential people from the affected area.",
    "Hold engines and thrusters if a hull contact is possible.",
    "Keep the sonar track — do not lose the contact.",
    "Stop over-side work and close nearby hatches.",
    "Log bearing, depth, and first detection time.",
  ],
  "comms-jamming": [
    "Switch to the backup communication channel.",
    "Confirm whether satcom, VHF, or both are affected.",
    "Continue local radar and visual watch — do not go blind.",
    "Log start time and which circuits failed.",
    "Retry restore on a set interval, not continuously.",
    "Escalate if the backup channel also fails.",
  ],
  "multi-domain-event": [
    "Get Support Center on a full engagement now.",
    "Split the watch: one person on air, one on surface if available.",
    "Keep both contacts on the picture; do not drop either track.",
    "Clear decks and set a tight exclusion.",
    "Do not fixate on the first contact you saw.",
    "Log both bearings and the time they appeared together.",
  ],
  "support-center-lost": [
    "Switch to the backup communication protocol.",
    "Continue local monitoring and logging — you are still on watch.",
    "Retry the link on a set interval, not continuously.",
    "Raise the local risk posture until the link returns.",
    "Use any secondary path if one is available.",
    "Log drop time and each restore attempt.",
  ],
};

export const FALLBACK_CRISIS_STEPS = [
  "Escalate to Support Center.",
  "Keep the situational picture live.",
  "Hold non-essential movement.",
  "Log time and every change.",
];
