import type { BillingType, PriceCategory } from "@/lib/price-book/types";

export type SeedItem = {
  itemCode: string;
  category: PriceCategory;
  subcategory?: string;
  name: string;
  description: string;
  unit: string;
  billingType: BillingType;
  listPrice?: number;
  minimumPrice?: number;
  applicablePlans?: string;
  includedInPlans?: string;
  internalNotes?: string;
};

export const LICENSE_PRICES = {
  LIGHT: 6000,
  ADVANCED: 18000,
  INTELLIGENCE: 42000,
  CUSTOM: 75000,
} as const;

export const PRICE_BOOK_VERSION = "2026.1";
export const PRICE_BOOK_NAME = "StarWall Price Book";

export const SEED_ITEMS: SeedItem[] = [
  {
    itemCode: "SW-LIC-LIGHT",
    category: "LICENSE",
    name: "StarWall LIGHT — Annual License",
    description: "Essential visibility license. Annual.",
    unit: "year",
    billingType: "ANNUAL",
    listPrice: LICENSE_PRICES.LIGHT,
    minimumPrice: LICENSE_PRICES.LIGHT,
    applicablePlans: "LIGHT",
  },
  {
    itemCode: "SW-LIC-ADVANCED",
    category: "LICENSE",
    name: "StarWall ADVANCED — Annual License",
    description: "Integrated protection license. Annual.",
    unit: "year",
    billingType: "ANNUAL",
    listPrice: LICENSE_PRICES.ADVANCED,
    minimumPrice: LICENSE_PRICES.ADVANCED,
    applicablePlans: "ADVANCED",
  },
  {
    itemCode: "SW-LIC-INTELLIGENCE",
    category: "LICENSE",
    name: "StarWall INTELLIGENCE — Annual License",
    description: "Adaptive intelligence license. Annual.",
    unit: "year",
    billingType: "ANNUAL",
    listPrice: LICENSE_PRICES.INTELLIGENCE,
    minimumPrice: LICENSE_PRICES.INTELLIGENCE,
    applicablePlans: "INTELLIGENCE",
  },
  {
    itemCode: "SW-LIC-CUSTOM",
    category: "LICENSE",
    name: "StarWall CUSTOM — Annual License",
    description: "Mission-specific license. Starting reference only; scope the figure.",
    unit: "year",
    billingType: "ANNUAL",
    listPrice: LICENSE_PRICES.CUSTOM,
    applicablePlans: "CUSTOM",
    internalNotes: "Starting reference. Do not treat as a fixed package price.",
  },
  {
    itemCode: "SW-INT-STANDARD",
    category: "INTEGRATION",
    subcategory: "STANDARD",
    name: "Standard Integration",
    description: "Camera system, AIS, NMEA source, standard supported sensor, environmental sensor.",
    unit: "each",
    billingType: "ONE-TIME",
  },
  {
    itemCode: "SW-INT-ADVANCED",
    category: "INTEGRATION",
    subcategory: "ADVANCED",
    name: "Advanced Integration",
    description: "Radar, sonar, access control, communications, complex sensor source.",
    unit: "each",
    billingType: "ONE-TIME",
  },
  {
    itemCode: "SW-INT-CUSTOM",
    category: "INTEGRATION",
    subcategory: "CUSTOM",
    name: "Custom Integration",
    description: "Proprietary, unsupported, vendor-specific, custom API, or legacy equipment. Engineering estimate plus integration charge.",
    unit: "each",
    billingType: "CUSTOM",
  },
  {
    itemCode: "SW-HW-RADAR",
    category: "HARDWARE",
    subcategory: "DETECTION",
    name: "Radar",
    description: "Detection radar. Component, not a bundled tier.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-CAMERA",
    category: "HARDWARE",
    subcategory: "DETECTION",
    name: "Camera",
    description: "Visible-spectrum camera.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-THERMAL",
    category: "HARDWARE",
    subcategory: "DETECTION",
    name: "Thermal Camera",
    description: "Thermal imaging camera.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-ACOUSTIC",
    category: "HARDWARE",
    subcategory: "DETECTION",
    name: "Acoustic Sensor",
    description: "Acoustic detection sensor.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-SONAR",
    category: "HARDWARE",
    subcategory: "DETECTION",
    name: "Sonar",
    description: "Underwater sonar.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-SPECTRAL",
    category: "HARDWARE",
    subcategory: "DETECTION",
    name: "Spectral Sensor",
    description: "Spectral analyzer / sensor.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-DETECT-OTHER",
    category: "HARDWARE",
    subcategory: "DETECTION",
    name: "Other Detection System",
    description: "Other detection hardware.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-NETWORK",
    category: "HARDWARE",
    subcategory: "COMMUNICATIONS",
    name: "Network Equipment",
    description: "Switching, routing, or site network hardware.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-SECURE-COMMS",
    category: "HARDWARE",
    subcategory: "COMMUNICATIONS",
    name: "Secure Communications",
    description: "Secure communications component.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-DATALINK",
    category: "HARDWARE",
    subcategory: "COMMUNICATIONS",
    name: "Data Link",
    description: "Data-link component.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-SATCOM",
    category: "HARDWARE",
    subcategory: "COMMUNICATIONS",
    name: "Satellite Connectivity Component",
    description: "Satellite connectivity hardware.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-COMMS-OTHER",
    category: "HARDWARE",
    subcategory: "COMMUNICATIONS",
    name: "Other Communications",
    description: "Other communications hardware.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-COMPUTE",
    category: "HARDWARE",
    subcategory: "COMPUTE",
    name: "StarWall Compute Unit",
    description: "Onboard or site compute for StarWall.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-EDGE",
    category: "HARDWARE",
    subcategory: "COMPUTE",
    name: "Edge Compute",
    description: "Edge compute unit.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-STORAGE",
    category: "HARDWARE",
    subcategory: "COMPUTE",
    name: "Storage",
    description: "Recording / archive storage.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-NET-CORE",
    category: "HARDWARE",
    subcategory: "COMPUTE",
    name: "Networking",
    description: "Compute-adjacent networking.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-POWER",
    category: "HARDWARE",
    subcategory: "COMPUTE",
    name: "Power Protection",
    description: "UPS / power protection.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-MOD-YACHT",
    category: "HARDWARE",
    subcategory: "AGRON MODULES",
    name: "Yacht Module",
    description: "AGRON yacht deployment module.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-MOD-FIXED",
    category: "HARDWARE",
    subcategory: "AGRON MODULES",
    name: "Fixed Site Module",
    description: "AGRON fixed-site module.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-MOD-MOBILE",
    category: "HARDWARE",
    subcategory: "AGRON MODULES",
    name: "Mobile Module",
    description: "AGRON mobile module.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-MOD-CONTAINER",
    category: "HARDWARE",
    subcategory: "AGRON MODULES",
    name: "Containerized Module",
    description: "AGRON containerized module. One hardware option among others.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-MOD-VEHICLE",
    category: "HARDWARE",
    subcategory: "AGRON MODULES",
    name: "Vehicle-Based Module",
    description: "AGRON vehicle-based module.",
    unit: "each",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-HW-MOD-CUSTOM",
    category: "HARDWARE",
    subcategory: "AGRON MODULES",
    name: "Custom Module",
    description: "Custom AGRON module.",
    unit: "each",
    billingType: "CUSTOM",
  },
  {
    itemCode: "SW-HW-CUSTOM",
    category: "HARDWARE",
    subcategory: "OTHER",
    name: "Custom Hardware",
    description: "Hardware not in the catalog.",
    unit: "each",
    billingType: "CUSTOM",
  },
  {
    itemCode: "SW-DEP-REMOTE",
    category: "DEPLOYMENT",
    name: "Remote Commissioning",
    description: "Remote commissioning. Travel is billed separately.",
    unit: "project",
    billingType: "ONE-TIME",
  },
  {
    itemCode: "SW-DEP-ONSITE",
    category: "DEPLOYMENT",
    name: "On-Site Commissioning",
    description: "On-site commissioning. Travel is billed separately.",
    unit: "project",
    billingType: "ONE-TIME",
  },
  {
    itemCode: "SW-DEP-INSTALL-DAY",
    category: "DEPLOYMENT",
    name: "Installation Day",
    description: "On-site installation day. Travel is billed separately.",
    unit: "day",
    billingType: "PER-DAY",
  },
  {
    itemCode: "SW-DEP-ENG-DAY",
    category: "DEPLOYMENT",
    name: "Engineering Deployment Day",
    description: "Engineering day on site or vessel.",
    unit: "day",
    billingType: "PER-DAY",
  },
  {
    itemCode: "SW-DEP-TRAVEL-DAY",
    category: "DEPLOYMENT",
    name: "Travel Day",
    description: "Travel day labor. Does not include airfare, hotel, or ground.",
    unit: "day",
    billingType: "PER-DAY",
  },
  {
    itemCode: "SW-DEP-SITE-SURVEY",
    category: "DEPLOYMENT",
    name: "Site Survey",
    description: "Site survey.",
    unit: "site",
    billingType: "PER-SITE",
  },
  {
    itemCode: "SW-DEP-VESSEL-SURVEY",
    category: "DEPLOYMENT",
    name: "Vessel Survey",
    description: "Vessel survey.",
    unit: "vessel",
    billingType: "PER-VESSEL",
  },
  {
    itemCode: "SW-DEP-SYS-TEST",
    category: "DEPLOYMENT",
    name: "System Testing",
    description: "System testing.",
    unit: "project",
    billingType: "ONE-TIME",
  },
  {
    itemCode: "SW-DEP-ACCEPT",
    category: "DEPLOYMENT",
    name: "Acceptance Testing",
    description: "Acceptance testing.",
    unit: "project",
    billingType: "ONE-TIME",
  },
  {
    itemCode: "SW-DEP-GOLIVE",
    category: "DEPLOYMENT",
    name: "Go-Live Support",
    description: "Go-live support window.",
    unit: "project",
    billingType: "ONE-TIME",
  },
  {
    itemCode: "SW-ENG-SOFTWARE",
    category: "ENGINEERING",
    name: "Software Engineering",
    description: "Software engineering labor.",
    unit: "hour",
    billingType: "PER-HOUR",
  },
  {
    itemCode: "SW-ENG-INTEGRATION",
    category: "ENGINEERING",
    name: "Integration Engineering",
    description: "Integration engineering labor.",
    unit: "hour",
    billingType: "PER-HOUR",
  },
  {
    itemCode: "SW-ENG-SYSTEMS",
    category: "ENGINEERING",
    name: "Systems Engineering",
    description: "Systems engineering labor.",
    unit: "hour",
    billingType: "PER-HOUR",
  },
  {
    itemCode: "SW-ENG-MARINE",
    category: "ENGINEERING",
    name: "Marine Integration",
    description: "Marine integration labor.",
    unit: "hour",
    billingType: "PER-HOUR",
  },
  {
    itemCode: "SW-ENG-NETWORK",
    category: "ENGINEERING",
    name: "Network Engineering",
    description: "Network engineering labor.",
    unit: "hour",
    billingType: "PER-HOUR",
  },
  {
    itemCode: "SW-ENG-HARDWARE",
    category: "ENGINEERING",
    name: "Hardware Engineering",
    description: "Hardware engineering labor.",
    unit: "hour",
    billingType: "PER-HOUR",
  },
  {
    itemCode: "SW-ENG-SECURITY",
    category: "ENGINEERING",
    name: "Security Engineering",
    description: "Security engineering labor.",
    unit: "hour",
    billingType: "PER-HOUR",
  },
  {
    itemCode: "SW-ENG-PM",
    category: "ENGINEERING",
    name: "Project Management",
    description: "Project management labor.",
    unit: "hour",
    billingType: "PER-HOUR",
  },
  {
    itemCode: "SW-ENG-CUSTOM",
    category: "ENGINEERING",
    name: "Custom Engineering",
    description: "Custom engineering labor.",
    unit: "hour",
    billingType: "PER-HOUR",
  },
  {
    itemCode: "SW-TRN-REMOTE",
    category: "TRAINING",
    name: "Remote Training Session",
    description: "Remote training session.",
    unit: "session",
    billingType: "ONE-TIME",
    includedInPlans: "INTELLIGENCE,CUSTOM",
  },
  {
    itemCode: "SW-TRN-ONSITE",
    category: "TRAINING",
    name: "On-Site Training Day",
    description: "On-site training day. Travel billed separately.",
    unit: "day",
    billingType: "PER-DAY",
  },
  {
    itemCode: "SW-TRN-OPERATOR",
    category: "TRAINING",
    name: "Operator Training",
    description: "Operator training.",
    unit: "session",
    billingType: "ONE-TIME",
    includedInPlans: "ADVANCED,INTELLIGENCE,CUSTOM",
  },
  {
    itemCode: "SW-TRN-ADMIN",
    category: "TRAINING",
    name: "Administrator Training",
    description: "Administrator training.",
    unit: "session",
    billingType: "ONE-TIME",
  },
  {
    itemCode: "SW-TRN-CAPTAIN",
    category: "TRAINING",
    name: "Captain / Management Training",
    description: "Captain or management briefing.",
    unit: "session",
    billingType: "ONE-TIME",
  },
  {
    itemCode: "SW-TRN-TECH",
    category: "TRAINING",
    name: "Technical Training",
    description: "Technical training.",
    unit: "session",
    billingType: "ONE-TIME",
  },
  {
    itemCode: "SW-TRN-CUSTOM",
    category: "TRAINING",
    name: "Custom Training",
    description: "Custom training.",
    unit: "session",
    billingType: "CUSTOM",
  },
  {
    itemCode: "SW-SUP-STANDARD",
    category: "SUPPORT",
    name: "Standard Support",
    description: "Business-hours software support. Not operational monitoring.",
    unit: "year",
    billingType: "ANNUAL",
    includedInPlans: "LIGHT,ADVANCED,INTELLIGENCE,CUSTOM",
  },
  {
    itemCode: "SW-SUP-PRIORITY",
    category: "SUPPORT",
    name: "Priority Support",
    description: "Priority technical response. Not continuous security monitoring.",
    unit: "year",
    billingType: "ANNUAL",
  },
  {
    itemCode: "SW-SUP-247-TECH",
    category: "SUPPORT",
    name: "24/7 Technical Support",
    description: "24/7 availability for defined technical incidents. Not continuous security monitoring.",
    unit: "year",
    billingType: "ANNUAL",
  },
  {
    itemCode: "SW-SUP-DEDICATED",
    category: "SUPPORT",
    name: "Dedicated Support",
    description: "Named support resources and a custom SLA once approved.",
    unit: "year",
    billingType: "ANNUAL",
  },
  {
    itemCode: "SW-SUP-CUSTOM-SLA",
    category: "SUPPORT",
    name: "Custom SLA",
    description: "Contract-specific SLA. Do not publish response or uptime numbers until entered and approved.",
    unit: "year",
    billingType: "CUSTOM",
  },
  {
    itemCode: "SW-MON-REMOTE",
    category: "MONITORING",
    name: "Remote Monitoring",
    description: "Operational monitoring. Separate from software support. Not bundled automatically.",
    unit: "year",
    billingType: "CUSTOM",
  },
  {
    itemCode: "SW-MON-SUPPORT-CENTER",
    category: "MONITORING",
    name: "AGRON Support Center Connection",
    description: "Connection to the AGRON Support Center. Operational service, not a software license.",
    unit: "year",
    billingType: "CUSTOM",
  },
  {
    itemCode: "SW-MON-ESCALATION",
    category: "MONITORING",
    name: "Event Escalation",
    description: "Event escalation coverage.",
    unit: "year",
    billingType: "CUSTOM",
  },
  {
    itemCode: "SW-MON-OPERATOR",
    category: "MONITORING",
    name: "Operator Assistance",
    description: "Operator assistance.",
    unit: "year",
    billingType: "CUSTOM",
  },
  {
    itemCode: "SW-MON-DEDICATED",
    category: "MONITORING",
    name: "Dedicated Monitoring",
    description: "Dedicated operational monitoring.",
    unit: "year",
    billingType: "CUSTOM",
  },
  {
    itemCode: "SW-MON-CUSTOM",
    category: "MONITORING",
    name: "Custom Operational Coverage",
    description: "Custom operational coverage.",
    unit: "year",
    billingType: "CUSTOM",
  },
  {
    itemCode: "SW-MS-VESSEL",
    category: "MULTI_SITE",
    name: "Additional Vessel",
    description: "Additional vessel on the same commercial record.",
    unit: "vessel",
    billingType: "PER-VESSEL",
  },
  {
    itemCode: "SW-MS-SITE",
    category: "MULTI_SITE",
    name: "Additional Site",
    description: "Additional site on the same commercial record.",
    unit: "site",
    billingType: "PER-SITE",
  },
  {
    itemCode: "SW-MS-ZONE",
    category: "MULTI_SITE",
    name: "Additional Operational Zone",
    description: "Additional operational zone.",
    unit: "zone",
    billingType: "PER-UNIT",
  },
  {
    itemCode: "SW-MS-INSTANCE",
    category: "MULTI_SITE",
    name: "Additional StarWall Instance",
    description: "Additional StarWall instance for another vessel or site.",
    unit: "each",
    billingType: "ANNUAL",
  },
  {
    itemCode: "SW-MS-OPS",
    category: "MULTI_SITE",
    name: "Central Operations Integration",
    description: "Central operations picture across vessels or sites.",
    unit: "project",
    billingType: "CUSTOM",
  },
  {
    itemCode: "SW-OPT-CONNECTIVITY",
    category: "OPTIONAL",
    name: "Connectivity Service",
    description: "Recurring connectivity. Price required.",
    unit: "year",
    billingType: "ANNUAL",
  },
  {
    itemCode: "SW-OPT-OTHER",
    category: "OPTIONAL",
    name: "Other Optional Service",
    description: "Other optional commercial service.",
    unit: "each",
    billingType: "CUSTOM",
  },
];
